# ===========================================================================
# Project:   TestApp
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :'core', :required => [:sproutcore]
config :all, :required => [:'core', :sproutcore]